import { Receipt } from 'lucide-react'
import type * as React from 'react'
import { FilterTabs } from '@/components/app/search-field'
import { SettleDialog } from '@/components/finance/settle-dialog'
import { StatCard } from '@/components/app/stat-card'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { EmptyState, PageHeader } from '@/components/ui/misc'
import { Table, TableWrapper, TBody, TD, TH, THead, TR } from '@/components/ui/table'
import { formatCurrency, formatDate, formatDueness } from '@/lib/format'
import { titleTone, type TitleView } from '@/server/present'

export interface TitlesPageProps {
  readonly kind: 'receivable' | 'payable'
  readonly rows: readonly TitleView[]
  readonly businessDate: string
  readonly totals: {
    readonly outstanding: string
    readonly overdue: string
    readonly overdueCount: number
    readonly dueToday: string
    readonly dueTodayCount: number
  }
  readonly canSettle: boolean
}

/**
 * Receivables and payables are the same screen with the arrow reversed, so
 * they are one component. The columns that differ -- who owes whom -- are the
 * only thing the `kind` decides.
 */
export function TitlesPage({
  kind,
  rows,
  businessDate,
  totals,
  canSettle,
}: TitlesPageProps): React.JSX.Element {
  const receivable = kind === 'receivable'

  return (
    <>
      <PageHeader
        title={receivable ? 'Receivables' : 'Payables'}
        description={
          receivable
            ? 'What customers owe. Titles are generated by invoicing, never created by hand.'
            : 'What you owe suppliers. Titles are generated when a delivery is received.'
        }
      />

      <section className="grid gap-4 sm:grid-cols-3">
        <StatCard
          label="Outstanding"
          value={formatCurrency(totals.outstanding)}
          hint={`${String(rows.length)} open title(s)`}
        />
        <StatCard
          label="Overdue"
          value={formatCurrency(totals.overdue)}
          hint={`${String(totals.overdueCount)} title(s) past due`}
          tone={totals.overdueCount > 0 ? 'danger' : 'positive'}
        />
        <StatCard
          label="Due today"
          value={formatCurrency(totals.dueToday)}
          hint={`${String(totals.dueTodayCount)} title(s)`}
          tone={totals.dueTodayCount > 0 ? 'warning' : 'neutral'}
        />
      </section>

      <Card>
        <CardHeader>
          <CardTitle>Open titles</CardTitle>
          <FilterTabs
            paramName="filter"
            options={[
              { value: '', label: 'Open' },
              { value: 'overdue', label: 'Overdue', count: totals.overdueCount },
              { value: 'today', label: 'Due today', count: totals.dueTodayCount },
              { value: 'all', label: 'All' },
            ]}
          />
        </CardHeader>

        <CardContent>
          {rows.length === 0 ? (
            <EmptyState
              icon={<Receipt className="size-5" />}
              title="Nothing here"
              description={
                receivable
                  ? 'Every receivable in this view is settled or cancelled.'
                  : 'Every payable in this view is settled or cancelled.'
              }
            />
          ) : (
            <TableWrapper>
              <Table>
                <THead>
                  <TR>
                    <TH>{receivable ? 'Customer' : 'Supplier'}</TH>
                    <TH>Title</TH>
                    <TH>Due</TH>
                    <TH>Status</TH>
                    <TH numeric>Amount</TH>
                    <TH numeric>Outstanding</TH>
                    {canSettle ? <TH className="w-28" /> : null}
                  </TR>
                </THead>
                <TBody>
                  {rows.map((title) => (
                    <TR key={title.id}>
                      <TD className="max-w-56 truncate font-medium">{title.partyName}</TD>
                      <TD className="max-w-64">
                        <span className="block truncate text-muted-foreground">
                          {title.description}
                        </span>
                        {title.instalments > 1 ? (
                          <span className="text-xs text-muted-foreground">
                            instalment {title.instalment}/{title.instalments}
                          </span>
                        ) : null}
                      </TD>
                      <TD className="whitespace-nowrap">
                        <span className="block">{formatDate(title.dueDate)}</span>
                        <span
                          className={
                            'text-xs ' + (title.overdue ? 'text-danger' : 'text-muted-foreground')
                          }
                        >
                          {formatDueness(title.dueDate, businessDate)}
                        </span>
                      </TD>
                      <TD>
                        <Badge tone={titleTone(title)} className="capitalize">
                          {title.overdue ? 'overdue' : title.status.replace('_', ' ')}
                        </Badge>
                      </TD>
                      <TD numeric className="text-muted-foreground">
                        {formatCurrency(title.amount)}
                      </TD>
                      <TD numeric className="font-medium">
                        {formatCurrency(title.outstanding)}
                      </TD>
                      {canSettle ? (
                        <TD>
                          {title.status === 'settled' || title.status === 'cancelled' ? null : (
                            <SettleDialog
                              kind={kind}
                              titleId={title.id}
                              partyName={title.partyName}
                              description={title.description}
                              outstanding={title.outstanding}
                            />
                          )}
                        </TD>
                      ) : null}
                    </TR>
                  ))}
                </TBody>
              </Table>
            </TableWrapper>
          )}
        </CardContent>
      </Card>
    </>
  )
}
