'use client'

import type { UseCaseName } from '@ledgerhand/domain'
import { AlertTriangle, ShieldAlert } from 'lucide-react'
import { useRouter } from 'next/navigation'
import * as React from 'react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogBody,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Field, Textarea } from '@/components/ui/field'
import { Skeleton } from '@/components/ui/misc'
import { performOperation, previewOperation } from '@/server/actions/operations'

export interface ConfirmOperationProps {
  readonly operation: UseCaseName
  readonly input: Record<string, unknown>
  readonly title: string
  readonly confirmLabel: string
  readonly trigger: React.ReactNode
  /** Adds a required free-text field merged into the input under this key. */
  readonly reasonField?: { readonly key: string; readonly label: string; readonly hint?: string }
  readonly successMessage?: string
  readonly destructive?: boolean
}

/**
 * ---------------------------------------------------------------------------
 * The approval card
 * ---------------------------------------------------------------------------
 * Before an irreversible operation runs, the domain is asked to describe what
 * it would do -- in a sentence generated by code, from the same input that is
 * about to be executed.
 *
 * This is deliberately the same mechanism the agent will use in phase 4. A
 * person approving the agent sees the identical sentence, produced by the
 * identical function, so nothing about the approval depends on trusting a
 * model's account of its own intentions.
 */
export function ConfirmOperation({
  operation,
  input,
  title,
  confirmLabel,
  trigger,
  reasonField,
  successMessage,
  destructive = true,
}: ConfirmOperationProps): React.JSX.Element {
  const router = useRouter()
  const [open, setOpen] = React.useState(false)
  const [preview, setPreview] = React.useState<string | null>(null)
  const [previewError, setPreviewError] = React.useState<string | null>(null)
  const [reason, setReason] = React.useState('')
  const [pending, startTransition] = React.useTransition()
  const [loadingPreview, setLoadingPreview] = React.useState(false)

  const payload = React.useMemo(
    () => (reasonField === undefined ? input : { ...input, [reasonField.key]: reason }),
    [input, reasonField, reason],
  )

  React.useEffect(() => {
    if (!open) return
    let cancelled = false
    setLoadingPreview(true)
    setPreviewError(null)

    void previewOperation(operation, {
      ...input,
      ...(reasonField ? { [reasonField.key]: '—' } : {}),
    })
      .then((result) => {
        if (cancelled) return
        if (result.ok) setPreview(result.data)
        else setPreviewError(result.message)
      })
      .finally(() => {
        if (!cancelled) setLoadingPreview(false)
      })

    return () => {
      cancelled = true
    }
    // The preview describes the operation, not the reason the user is typing.
  }, [open, operation])

  const reasonMissing = reasonField !== undefined && reason.trim().length < 3

  const confirm = (): void => {
    startTransition(async () => {
      const result = await performOperation(operation, payload)
      if (result.ok) {
        toast.success(successMessage ?? 'Done.')
        setOpen(false)
        setReason('')
        router.refresh()
      } else {
        toast.error(result.message)
      }
    })
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <span
        onClick={() => {
          setOpen(true)
        }}
        className="contents"
      >
        {trigger}
      </span>

      <DialogContent size="md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            {destructive ? <ShieldAlert className="size-4 text-danger" /> : null}
            {title}
          </DialogTitle>
          <DialogDescription>
            {destructive
              ? 'This operation cannot be undone without a compensating entry. Read what it will do before approving.'
              : 'Confirm the operation below.'}
          </DialogDescription>
        </DialogHeader>

        <DialogBody className="space-y-4">
          <div className="rounded-lg border border-border bg-surface-sunken p-3.5">
            {loadingPreview ? (
              <div className="space-y-2">
                <Skeleton className="h-3.5 w-full" />
                <Skeleton className="h-3.5 w-4/5" />
              </div>
            ) : previewError !== null ? (
              <p className="flex items-start gap-2 text-sm text-danger">
                <AlertTriangle className="mt-0.5 size-4 shrink-0" />
                {previewError}
              </p>
            ) : (
              <p className="text-sm leading-relaxed">{preview}</p>
            )}
          </div>

          {reasonField !== undefined ? (
            <Field
              label={reasonField.label}
              htmlFor="operation-reason"
              hint={reasonField.hint}
              required
            >
              <Textarea
                id="operation-reason"
                value={reason}
                onChange={(event) => {
                  setReason(event.target.value)
                }}
                placeholder="This goes on the permanent record."
                rows={3}
              />
            </Field>
          ) : null}
        </DialogBody>

        <DialogFooter>
          <Button
            variant="ghost"
            onClick={() => {
              setOpen(false)
            }}
            disabled={pending}
          >
            Cancel
          </Button>
          <Button
            variant={destructive ? 'destructive' : 'primary'}
            onClick={confirm}
            loading={pending}
            disabled={reasonMissing || previewError !== null}
          >
            {confirmLabel}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
