import type { JsonObject, JsonValue, RiskLevel } from '@ledgerhand/domain'
import type { Tool } from '@modelcontextprotocol/sdk/types.js'
import type { ToolSummary } from '../gateway/gateway.js'

/**
 * ---------------------------------------------------------------------------
 * Tools
 * ---------------------------------------------------------------------------
 * One tool per use case, derived from the descriptor rather than written out
 * again here. The schema advertised to the model is the schema that will
 * reject it, which is the only arrangement where "the tool definition is
 * accurate" cannot drift.
 *
 * Note what is NOT done: the zod schema is not handed to the SDK for
 * conversion. Several inputs carry cross-field rules -- "from must not be
 * after to", "give me an id or a number" -- and a converter that meets one of
 * those either throws or drops it. The domain already produces the JSON Schema
 * it wants published, so that is what gets published.
 */

export const IDEMPOTENCY_KEY = 'idempotency_key'

const IDEMPOTENCY_DESCRIPTION =
  'Optional. Send a unique key to make retrying this call safe: a repeat with the same key returns the original result instead of acting twice. Reusing a key with different arguments is an error.'

/** The name of the tool that describes a destructive operation without running it. */
export const PREVIEW_TOOL = 'preview_operation'

function riskNote(risk: RiskLevel): string {
  switch (risk) {
    case 'read':
      return 'Risk: read. Changes nothing.'
    case 'write':
      return 'Risk: write. Changes data, and is undone by an ordinary operation.'
    case 'destructive':
      return `Risk: destructive. It moves money, consumes fiscal numbering or overwrites a recorded fact, so a person is asked to confirm it before it runs. Call ${PREVIEW_TOOL} first if you want to show the effect without performing it.`
  }
}

/**
 * Writes gain an `idempotency_key`. Reads do not: replaying a read would
 * answer with a stale number, which is worse than reading again.
 */
export function withIdempotencyKey(schema: JsonObject, risk: RiskLevel): JsonObject {
  if (risk === 'read') return schema

  const properties = (schema['properties'] ?? {}) as JsonObject
  return {
    ...schema,
    type: 'object',
    properties: {
      ...properties,
      [IDEMPOTENCY_KEY]: { type: 'string', maxLength: 128, description: IDEMPOTENCY_DESCRIPTION },
    },
  }
}

export function toMcpTool(summary: ToolSummary): Tool {
  return {
    name: summary.name,
    title: summary.title,
    description: `${summary.summary}\n\n${riskNote(summary.risk)}`,
    inputSchema: withIdempotencyKey(summary.inputSchema, summary.risk) as Tool['inputSchema'],
    annotations: {
      title: summary.title,
      readOnlyHint: summary.risk === 'read',
      destructiveHint: summary.risk === 'destructive',
      // True only in the sense the protocol means it: repeating the call with
      // the same idempotency key does not repeat the effect.
      idempotentHint: summary.risk !== 'read',
      openWorldHint: false,
    },
  }
}

export const previewTool: Tool = {
  name: PREVIEW_TOOL,
  title: 'Preview an operation',
  description:
    'Returns a sentence describing what an operation would do, without doing it. The sentence is generated by the ERP from the arguments you pass, so it is the description a person will be asked to approve. Returns null for operations that change nothing.',
  inputSchema: {
    type: 'object',
    properties: {
      operation: { type: 'string', description: 'The name of the tool you intend to call.' },
      input: { type: 'object', description: 'The arguments you intend to pass to it.' },
    },
    required: ['operation', 'input'],
    additionalProperties: false,
  },
  annotations: {
    title: 'Preview an operation',
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false,
  },
}

export interface SplitArguments {
  readonly input: JsonObject
  readonly idempotencyKey: string | null
}

/**
 * The idempotency key is the transport's business, not the domain's, so it is
 * taken out before the arguments are validated. Leaving it in would make every
 * use case schema reject it as an unknown property.
 */
export function splitArguments(raw: unknown): SplitArguments {
  if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) {
    return { input: {}, idempotencyKey: null }
  }

  const { [IDEMPOTENCY_KEY]: key, ...input } = raw as Record<string, JsonValue>
  return {
    input: input,
    idempotencyKey: typeof key === 'string' && key.trim() !== '' ? key : null,
  }
}
